use_default_settings: true

server:
  secret_key: "biomed_secure_key_11851"
  limiter: false
  image_proxy: true

search:
  safe_search: 1
  formats:
    - html
    - json

engines:
  - name: pubmed
    engine: pubmed
    shortcut: pm
